version: '3'

services:
  postgresdb:
    container_name: ${COMPOSE_PROJECT_NAME}_db
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "127.0.0.1:${DB_PROXY_PORT}:5432"
    restart: unless-stopped
    volumes:
      - ./db-data/:/var/lib/postgresql/data

  appserver:
    container_name: ${COMPOSE_PROJECT_NAME}_server
    user: ${USER_UID}:${USER_GID}
    image: ${DOCKER_IMAGE_URL}
    environment:
      DB_PORT: 5432
      DB_HOST: ${COMPOSE_PROJECT_NAME}_db
    env_file:
      - .env
    ports:
      - "127.0.0.1:${LISTEN_PORT}:3030"
    depends_on:
      - postgresdb
    restart: unless-stopped
    volumes:
      - ./static/:/appdata/static
      - ./media/:/appdata/media
    logging:
      driver: syslog
      options:
        syslog-address: "udp://localhost:514"
        tag: "${COMPOSE_PROJECT_NAME}_server|{{.ContainerName}}|{{.FullID}}"

  app-indexer:
    container_name: ${COMPOSE_PROJECT_NAME}_index_blocks
    user: ${USER_UID}:${USER_GID}
    image: ${DOCKER_IMAGE_URL}
    command: /app/docker/remote/entrypoint-index.sh
    environment:
      DB_PORT: 5432
      DB_HOST: ${COMPOSE_PROJECT_NAME}_db
    env_file:
      - .env
    depends_on:
      - postgresdb
    restart: unless-stopped
    volumes:
      - ./static/:/appdata/static
      - ./media/:/appdata/media
    logging:
      driver: syslog
      options:
        syslog-address: "udp://localhost:514"
        tag: "${COMPOSE_PROJECT_NAME}_index_blocks|{{.ContainerName}}|{{.FullID}}"

  app-prune:
    container_name: ${COMPOSE_PROJECT_NAME}_prune_blocks
    user: ${USER_UID}:${USER_GID}
    image: ${DOCKER_IMAGE_URL}
    command: /app/docker/remote/entrypoint-prune.sh
    environment:
      DB_PORT: 5432
      DB_HOST: ${COMPOSE_PROJECT_NAME}_db
    env_file:
      - .env
    depends_on:
      - postgresdb
    restart: unless-stopped
    volumes:
      - ./static/:/appdata/static
      - ./media/:/appdata/media
    logging:
      driver: syslog
      options:
        syslog-address: "udp://localhost:514"
        tag: "${COMPOSE_PROJECT_NAME}_prune_blocks|{{.ContainerName}}|{{.FullID}}"

